name: Python Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: qe-ubuntu20

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install --no-cache-dir -r requirements.txt && pip install -e .
          pip install pytest pytest-cov
          pip install tests/resources/cmlapi.tar.gz

      - name: Run tests with coverage
        run: |
          pytest --cov=./ft tests/

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./.coverage

      - name: Check coverage
        run: |
          coverage report --fail-under=10
